integratedmodelling/klab

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/ogc/integration/Postgis.java
There is an issue with WKT being returned from the database.  We now explicitly request the geom to be returned as binary.  We then handle the conversion to Geometry via the WKBReader.
> Postgis sql statements now requesting geom as binary

- klab.hub/pom.xml
- klab.node/pom.xml
- pom.xml
- products/cloud/pom.xml
> [#16] Show JVM settings on startup

- Jenkinsfile
Use latest `klab-base-16` image
> Issue 25 klab base

- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/api/API.java
- klab.authentication/src/main/java/org/integratedmodelling/klab/auth/Role.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/EngineAuthResponeFactory.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/ModifyUserAccountStatusTask.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/RemoveRoleTask.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/SetRoleTask.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/TaskType.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/User.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/exception/LockedUserException.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/payload/LoginResponse.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/repository/UserRepository.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tasks/controllers/ModifyRolesController.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tasks/controllers/ModifyUserAccountStatusController.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tasks/services/CommandFactory.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tasks/services/TaskFactory.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tokens/services/UserAuthTokenServiceImpl.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/controllers/UserAccountStatusController.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/controllers/UserRoleEntryController.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/services/UserAccountStatusService.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/services/UserAccountStatusServiceImpl.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/services/UserRoleEntryService.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/services/UserRoleEntryServiceImpl.java
- Added role Manager.
- Added status suspended as "locked".
- Allow to modify the roles of a user via a REST call.
- Allow to modify the status of a user via a REST call.
> Im 69 users add suspended status add role manager

- components/klab.component.alignment/pom.xml
- klab.engine/pom.xml
- klab.hub/pom.xml
Fix vulnerabilities marked as _Critical_ by Dependabot
> Issue 27 dependabot

- klab.node/pom.xml
- klab.node/src/main/java/org/integratedmodelling/klab/node/NodeApplication.java
- products/semantic/pom.xml
- products/semantic/src/main/java/org/integratedmodelling/klab/semantic/SemanticServerApplication.java
> [#40] Remove k8s annotations

- klab.engine/pom.xml
> Upgrade Groovy to 3.0.11

- products/cloud/src/main/resources/bootstrap-consul.yml
Enable the possibility of service re-registration after failure.
Closes #53
> [#53] Enable service re-registration

- klab.hub/src/main/java/org/integratedmodelling/klab/hub/agreements/controllers/UserAgreementController.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/agreements/services/AgreementServiceImpl.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/agreements/services/UserAgreementService.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/agreements/services/UserAgreementServiceImpl.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/Agreement.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/EngineAuthResponeFactory.java
`revokedDate` and `UserAgreementController` refactorized.
> Im 81 check valid user after authentication

- klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/ProfileResource.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/payload/EngineProfileResource.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/payload/LoginResponse.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tokens/services/UserAuthTokenServiceImpl.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/controllers/UserProfileController.java
Different response if the authentication is made by a user or a remote engine.
Need to solve an issue with expiration for groups to check that everything works
> Solve authentication problem from remote engine

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACAssetParser.java
- adapters/klab.ogc/src/test/java/org/integratedmodelling/klab/ogc/stac/test/STACParsingTest.java
Check [here](https://github.com/stac-extensions/classification) the extension.
This pull request adds the parser method, but does not change the adapter itself.
> Im 226 implement parsing of classification extension

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
When multiple STAC items are found, the encoder will choose the best merging strategy depending on the context provided.
> Im 233 determine strategy to merge stac resources

- Jenkinsfile
Enable push products for `develop`
> IM-203 Enable push products stage

- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/rest/ExternalAuthenticationCredentials.java
- components/klab.component.random/src/main/java/org/integratedmodelling/random/adapters/RecreationIDB.java
- components/klab.component.random/src/main/java/org/integratedmodelling/random/adapters/RecreationIDBAdapter.java
Store the API key for RIDBAdapter using the credentials command.
> Im 280 store the api key for recreation idb

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/ogc/STACAdapter.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACAssetParser.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACImporter.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACService.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACUtils.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACValidator.java
Some cleanup tasks for STAC:
- Read Geometry from HM
- Remove unnecessary features (store multiple collections, dead code)
- Improve parsing of JSON (exception managing, taking alternatives into account)
This code could be refactorized to be in line with our style. However, I would prefer to do that after the code review so the real changes are visible.
> Im 294 clean and move stac parsing functionalities to the horton machine project

- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/kim/api/IKimProject.java
- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/api/services/IActorsService.java
- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/rest/SessionReference.java
- klab.engine/src/main/java/org/integratedmodelling/klab/Actors.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/runtime/actors/behavior/Behavior.java
- klab.engine/src/main/java/org/integratedmodelling/klab/engine/runtime/Session.java
Added logic to avoid showing public applications that are not allowed for users.
It reads the `klab.permissions' parameter in the `META-INF/klab.properties' of KIM projects.
> Im 291 capabilities public endpoint must filter app by user s groups

- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/api/API.java
- klab.engine/src/main/java/org/integratedmodelling/klab/engine/rest/controllers/engine/EnginePublicController.java
Two requests for the API from NBSoil partners are implemented:
- return the value of a lat/lon point of observation
- Information about resources that was used in the observation
> Im 354 analyze nb soil partner requests

- klab.hub/src/main/java/org/integratedmodelling/klab/hub/tokens/services/UserAuthTokenServiceImpl.java
> Im 335 check and fix update last login date and last connection date in hub

- klab.engine/src/main/java/org/integratedmodelling/klab/components/runtime/actors/RuntimeBehavior.java
- klab.engine/src/main/java/org/integratedmodelling/klab/documentation/extensions/table/TableArtifact.java
Reference to integratedmodelling/aries-team-issue/#54
Expose `Space` of resolution scale
> Im 368 aries team issue 54

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACCollectionParser.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACImporter.java
- adapters/klab.ogc/src/test/java/org/integratedmodelling/klab/ogc/stac/test/STACImporterTest.java
Added more checks and debugging information to the STAC adapter.
> Im 359 digital earth resource from stac catalogue cannot be imported

- klab.engine/src/main/java/org/integratedmodelling/klab/data/table/LookupTable.java
Resolve presence of duplicate value in histogram due to multiple condition for the same result
> Im 401 mismatch of class labels vs colormap in k.explorer

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/Valhalla.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java
- klab.engine/src/main/resources/components/org.integratedmodelling.network/services/network.kdl
Changelog:
- Valhalla server can now be defined as any URL.
> Im 415 make valhalla available for valencia

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/osm/OSMSubjectInstantiator.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/Valhalla.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/ValhallaRuntimeEnvironment.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java
- klab.engine/src/main/resources/components/org.integratedmodelling.network/services/network.kdl
Changelog:
- Discard routes that are known to be outside the limits before calling Valhalla.
- Refactorization of the affected classes.
- Remove unused features that bloated the code.
> Im 431 provide information about the nodes at network export

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/osm/OSMSubjectInstantiator.java
This changelog is smaller that what I wanted to do originally in the branch. The issue of getting buildings from a large and complex polygon is easily solved by increasing the timeout. However, I fixed one issue:
- Avoid failing after a single Overpass endpoint didn't return a successful response. This way, the system can try the next endpoint.
> Continue with another overpass endpoint instead of throwing an exception

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/osm/OSMQuery.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/osm/OSMSubjectInstantiator.java
- klab.engine/src/main/resources/components/org.integratedmodelling.geospace/services/osm.kdl
Changelog:
- Allow conditional filtering for OSM queries.
> Im 439 add conditional filters to osm queries

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/ogc/vector/files/VectorImporter.java
Add condition in case of polygons like `building` to permit add shape file format to possible export formats
> Add condition to permit export in case of polygons

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/Rasterizer.java
Changelog:
- Fixed issue of drawing holes over existing rasters. This has been done by dividing polygons with holes into triangles.
> Im 437 polygons not detected by k.lab

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/Valhalla.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/ValhallaConfiguration.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/services/IsochroneInstantiator.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java
- klab.engine/src/main/resources/components/org.integratedmodelling.network/services/isochrone.kdl
- klab.engine/src/main/resources/components/org.integratedmodelling.network/services/network.kdl
Changeset:
- Instantiate isochrones using Valhalla
- Use isochrones to filter out unreachable nodes while calculating networks
> Im 443 allow isochrone requests in valhalla

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/ogc/vector/files/VectorEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACCollectionParser.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACImporter.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACService.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACValidator.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/extensions/STACIIASAExtension.java
- adapters/klab.ogc/src/main/resources/ogc/prototypes/stac.kdl
- adapters/klab.ogc/src/test/java/org/integratedmodelling/klab/ogc/stac/test/STACValidatorTest.java
Changelog:
- Allow to download data from the IIASA endpoint
- Choose the STAC resource type depending on the endpoint
- Support asset-less STAC resources
> Im 465 support asset less stac resources

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/ogc/vector/files/VectorImporter.java
Changeset:
- Allow downloading vector observations as GeoJSONs.
> Im 474 export vector observations as geojson

- klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java
- klab.engine/src/main/resources/components/org.integratedmodelling.network/services/network.kdl
Changes:
- Fixed trying to define an isochrone while `timeThreshold` was `null` 
- Made the units used for Valhalla (input/output) explicit
- Set routing time input as seconds
> Valhalla travel connection gives error this.time threshold is null

- klab.engine/pom.xml
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/Rasterizer.java
- pom.xml
Changelog:
- Bump JTS to 1.20
- Get back the changes from https://github.com/integratedmodelling/klab/pull/210/files
> Im 485 error unable to find a convex corner

- adapters/klab.adapter.copernicus/src/main/java/org/integratedmodelling/adapter/copernicus/datacubes/CopernicusCDSDatacube.java
Modify the Copernicus adapter to use the new CDS API.
Thanks to [this](https://forum.ecmwf.int/t/ecmwf-apis-faq-api-data-documentation/6880) post we were able to implement this.
Removed the user code from the `application.yml` as it is no longer needed.
> IM-543 copernicus credential changes

- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/Valhalla.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/ValhallaOutputDeserializer.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/routing/services/IsochroneInstantiator.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/MatrixRelationshipInstantiator.java
- klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java
- klab.engine/src/main/resources/components/org.integratedmodelling.network/services/network.kdl
Changelog:
- Added the matrix query instantiator.
- Defined Valhalla matrix input, request and parsing.
- Use the output to generate networks.
- Send the requests in chunks according to max_locations parameter.
- Added documentation for Valhalla matrix and updated Valhalla related ones.
> Im 507 implement a matrix query via valhalla

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACAssetParser.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACCollectionParser.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACUtils.java
Changelog:
- Allow the analysis of the item type via `href`
- Import static collections
- Read static collections
- Filter out items from static collections outside the context
> Im 511 read static catalog items

- .gitignore
- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/api/API.java
- api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/rest/UserAuthenticationRequest.java
- klab.engine/pom.xml
- klab.engine/src/main/java/org/integratedmodelling/klab/engine/rest/api/EngineProperties.java
- klab.hub/pom.xml
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/security/WebSecurityConfiguration.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/controllers/UserAuthenticationController.java
- pom.xml
- products/cloud/src/main/java/org/integratedmodelling/klab/engine/services/HubUserService.java
- products/cloud/src/main/resources/bootstrap.yml.example
https://integratedmodelling.atlassian.net/browse/IM-575
> Im 575 add keycloak authentication to api

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/ogc/RasterAdapter.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/raster/files/RasterEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/raster/files/RasterValidator.java
- adapters/klab.ogc/src/main/resources/ogc/prototypes/openeo.kdl
- adapters/klab.ogc/src/main/resources/ogc/prototypes/raster.kdl
- adapters/klab.ogc/src/main/resources/ogc/prototypes/stac.kdl
- adapters/klab.ogc/src/main/resources/ogc/prototypes/wcs.kdl
Changelog:
- Added a bandmixing operation for the raster resources and dependent adapters.
- Operations for getting the max, min, average and summed values, and the band number of the min or max value.
> Im 631 get cell with max min or avg value from multiband raster

- klab.hub/pom.xml
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/exception/HubException.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/exception/HubExceptionHandler.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/exception/HubHttpException.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/security/WebSecurityConfiguration.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/vault/VaultConfig.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/vault/VaultController.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/vault/VaultService.java
- klab.hub/src/main/resources/application.yml.example
https://integratedmodelling.atlassian.net/jira/software/c/projects/IM/boards/1?assignee=632321278738d3ca32266544&selectedIssue=IM-674
> Add-Vault-as-password-token-manager

- klab.engine/src/main/java/org/integratedmodelling/klab/components/runtime/actors/RuntimeBehavior.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/security/WebSecurityConfiguration.java
- klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/controllers/UserEmailController.java
https://integratedmodelling.atlassian.net/browse/IM-730?atlOrigin=eyJpIjoiODRiYzRiYjAyMjk4NDg2YmIyYzM0ZWQ5MDQxMjg5YzEiLCJwIjoiaiJ9
Can be tested in: https://integration.integratedmodelling.org/modeler
> IM-730 Send emails authentication with bearer token and own jwtToken

- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/openeo/OpenEO.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/openeo/OpenEOEncoder.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/extensions/STACIIASAExtension.java
- adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/extensions/WEEDECDCExtension.java
- adapters/klab.ogc/src/test/java/org/integratedmodelling/klab/ogc/test/OpenEOTests.java
Added the non WEED project specific changes to the main branch of k.LAB.
> Im 707 set non weed specific improvements into the develop branch
