kim/org.integratedmodelling.kim.target/org.integratedmodelling.kim.target.target
kim/org.integratedmodelling.kim/META-INF/MANIFEST.MF

* This is a deprecated bundle, not present in `org.eclipse.xtext.sdk` feature anymore.
* The Xtext team recommends (since version 2.27.0) to switch to the "new" generator
* Removing those references and testing via maven `mvn clean install -DskipTests` seems to work just fine

[#22] Remove references to `org.eclipse.xtext.generator` bundle

---

api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/utils/Utils.java
klab.core.api/src/main/java/org/integratedmodelling/klab/api/utils/Utils.java
klab.node/pom.xml
klab.node/src/main/java/org/integratedmodelling/klab/node/resources/ResourceCatalog.java
products/semantic/pom.xml

The original library is not up to date and contains several vulnerabilities.

Remove dependencies from com.google.html.types

---

klab.engine/src/main/java/org/integratedmodelling/klab/engine/rest/controllers/engine/EngineViewController.java

This fixes the geotiff download, which from the view/data should also create the style file.
But I am still a bit puzzeled about why the response always chooses *.zip as extension. Wasn't able to find out where that is picked.

fix for proper style export in zip when downloading observations

---

klab.engine/src/main/java/org/integratedmodelling/klab/utils/FileUtils.java
products/cloud/src/main/java/org/integratedmodelling/klab/engine/RemoteEngine.java

* We have 8GB allocated for the `/tmp` folder in remote engine containers. We want to clean up temporary files of old observations.
* The `closeExpiredSessions` method is triggered every minute, no need to call the same code on session logout

IM-110 Delete temporary files as part of remote session clean-up

---

products/cli/pom.xml

We use maven-dependency-plugin/copy-dependencies to move all the jars to the `lib/` folder. There are 2 different jars that provide the same packages `javax.annotation.*`
The jars provided by Eclipse are signed, leading to the signer exception.
Closes #55

[#55] Exclude javax.annotation artifact from copies jars

---

api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/api/PublicAPI.java
klab.engine/src/main/java/org/integratedmodelling/klab/engine/rest/controllers/base/SwaggerConfig.java
klab.engine/src/main/java/org/integratedmodelling/klab/engine/rest/controllers/engine/EnginePublicController.java

- Introduce a new `@PublicAPI` annotation, used for filtering the public controllers

[#72] Expose only public api to Swagger

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACService.java
adapters/klab.ogc/src/main/resources/ogc/prototypes/stac.kdl

Minor change to get closer to the STAC naming convention.
Related to a [PR](https://github.com/TheHortonMachine/hortonmachine/pull/89) for the HortonMachine project.

Manage STAC Assets via id instead of band title

---

.gitignore
.mvn/maven.config
.mvn/wrapper/maven-wrapper.properties
Jenkinsfile
mvnw
mvnw.cmd

* Use Maven Wrapper to pin the version (3.9.5)
* Change the Jenkins agent to use `./mvnw` instead of `mvn` - The new agent only has JDK17, git, curl.
* Configure by default `-B` (batch mode, no ansi colors) and `-ntp` (no transfer progress)
I also tested the `mvnw.cmd` on Windows

Im 252 maven wrapper

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACAssetParser.java
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACValidator.java
adapters/klab.ogc/src/test/java/org/integratedmodelling/klab/ogc/stac/test/STACParsingTest.java

With these changes, the adapter will try to get the type of the values in two ways:
- Read the field `data_type` from the standard https://github.com/stac-extensions/raster?tab=readme-ov-file#data-types 
- Infer the value type by reading the values at `file:values`.

Im 289 stac classification error

---

components/klab.component.random/src/main/java/org/integratedmodelling/random/adapters/RecreationIDBAdapter.java

A pretty simple change: we just don't add those recreation areas inside the context.
Side note: the indentation mixes tabs and spaces, I am aware of that. Before merging the changes at #129, we should refactor everything to our preferred formatting.

Filter out recreation areas outside the context

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/openeo/OpenEO.java
api/org.integratedmodelling.klab.api/src/org/integratedmodelling/klab/rest/ExternalAuthenticationCredentials.java
klab.authentication/src/main/java/org/integratedmodelling/klab/Authentication.java
klab.engine/src/main/java/org/integratedmodelling/klab/auth/Authorization.java
klab.engine/src/main/java/org/integratedmodelling/klab/cli/commands/credentials/Set.java
klab.engine/src/main/resources/cli/commands/credentials.kdl

Upgraded the credential schema:
- Extra flexibility on defining the command
- Use an alternative ID for each credential
- Read credentials via ID or URL
- Semi-automatic update of credentials

Im 339 avoid using the url as the key of credentials

---

Jenkinsfile
Jenkinsfile.withParams
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
adapters/klab.ogc/src/test/java/org/integratedmodelling/klab/ogc/test/StacTest.java
components/klab.component.hydrology/src/main/java/org/integratedmodelling/geoprocessing/remotesensing/SentinelResolver.java
klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/osm/OSMQuery.java
klab.engine/src/main/java/org/integratedmodelling/klab/components/geospace/processing/osm/OSMSubjectInstantiator.java
klab.engine/src/main/resources/components/org.integratedmodelling.geospace/services/osm.kdl
pom.xml

Changelog:
- Make the overpass queries use the polygon of the context instead of the bbox.
- Bump the HortonMachine version and increase the JIB timeout.

Im 416 filter out osm features outside the context

---

klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java

Changelog:
- Read the routing parameters from the String value instead of the Enum name.

Fix wrong case in routing parameters

---

klab.engine/src/main/java/org/integratedmodelling/klab/components/network/model/Network.java

Fixed a small bug: the `emergentObservation` variable could be null and cause a classic `NullPointerException`, impeding the export of GEXF files.

Avoid calling a null emergent observation

---

klab.engine/src/main/java/org/integratedmodelling/klab/components/network/model/Network.java
klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/ConfigurableRelationshipInstantiator.java

Changelog:
- Allowed download of connections as CSV.
- Added mock metadata to `network.connect`.
- Export metadata from the nodes.
This branch is still WIP, but some features are needed in the develop branch.

Im 431 provide information about the nodes at network export and export CSV

---

klab.engine/src/main/java/org/integratedmodelling/klab/components/network/services/RoutingRelationshipInstantiator.java
klab.engine/src/main/resources/components/org.integratedmodelling.network/services/network.kdl

Waiting for large networks to be finished took a long time and made more than a few modellers nervous as they got no feedback while waiting. This small change attempts to solve that:
Changelog:
- Log the progress of the Valhalla network after reaching a new decile of the potential routes. 
- Set the logging threshold as a parameter.

Im 436 log the progress of the valhalla network

---

Jenkinsfile

* By default other branches will not have a `jib:build`
* Developers can opt-in by addding `[docker build]` in their commit message

IM-455 Enable Docker build for `master` and `develop` branch

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACAssetParser.java
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACCollectionParser.java

The valid data types were obtained from the following link: https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#common-media-types-in-stac
At this time, the permitted types are as follows:
- GeoTIFF
- Cloud Optimized GeoTIFF
- GeoJSON

Im 521 allow more media types in stac

---

adapters/klab.ogc/pom.xml
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
adapters/klab.ogc/src/main/resources/ogc/prototypes/stac.kdl
pom.xml

Changelog:
- Updated the AWS dependencies to the new distribution
- Changed the HortonMachine snapshot to a new version
- Add `s3BucketRegion` parameter to STAC resources

Bump and adapt AWS dependency to version 2.0

---

adapters/klab.ogc/pom.xml
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java

As @iperdomo suggested in the previous PR #222, it is possible to switch to a synchronous client. Easier to use and maintain and a little bit faster.

Switch from Async to Synchronous S3 client

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACCollectionParser.java
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACEncoder.java
adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/stac/STACImporter.java
adapters/klab.ogc/src/main/resources/ogc/prototypes/stac.kdl
klab.engine/pom.xml
klab.engine/src/main/java/org/integratedmodelling/klab/utils/s3/S3RegionResolver.java
klab.engine/src/test/java/org/integratedmodelling/klab/test/utils/S3RegionResolverTest.java

Changelog:
- The AWS region of the bucket is now obtained by analyzing the URL of the asset.
- Removed `item_assets` compatibility, as it lacked the `href` field needed for getting the bucket.
- Changed the name of `s3BucketRegion` to `awsRegion` and removed it as a parameter at the importer.

Im 542 get s3 region by analyzing the asset href

---

klab.hub/src/main/java/org/integratedmodelling/klab/hub/api/ModifyGroupsTask.java
klab.hub/src/main/java/org/integratedmodelling/klab/hub/emails/controllers/EmailController.java
klab.hub/src/main/java/org/integratedmodelling/klab/hub/repository/UserRepository.java
klab.hub/src/main/java/org/integratedmodelling/klab/hub/security/keycloak/service/KeycloakSecurityService.java
klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/controllers/UserProfileController.java
klab.hub/src/main/java/org/integratedmodelling/klab/hub/users/services/UserTagServiceImpl.java
klab.hub/src/main/resources/application.yml.example

**Jira issue:** https://integratedmodelling.atlassian.net/browse/IM-562
The changes are in testing.integratedmodelling.org/hub

IM-562 fix: Bug with uppercase/lowercase names

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/openeo/OpenEOEncoder.java

A fix for a ClassCastException at OpenEO during engine initialization. A simple check avoids breaking the start-up process.

Catch Credentials exception at OpenEO resource validation

---

klab.engine/pom.xml

Updating the `org.apache.poi` dependency to the latest version solved the issue with table creation.
It also resolved the issue with the `table` button in the apps.

Solve bug in aries-team-issue #92

---

adapters/klab.ogc/src/main/java/org/integratedmodelling/klab/raster/wcs/WCSService.java

This fixes a bug while trying to import WCS resources from IDEAM. The object used to store some of the data obtained from the WCS parsing wasn't supported in k.LAB.
Reference: https://github.com/integratedmodelling/aries-team-issues/issues/94.

Use iterable for WCS parsing
